#!/usr/bin/perl -w

package esmith;

use strict;
use Errno;
use esmith::templates;
use esmith::util;

# sql symlink
symlink "/var/www/html/faxweb/sql/faxweb2.sql",
    "/etc/e-smith/sql/init/10faxweb2.sql";

system ("/sbin/service mysql.init start"); 

exit (0);
